name: E2E Tests

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SAFE_CLI_VERSION: "0.9.0"
  IS_CI: true
  # No CSC Keys etc as PRs dont have access to this.
  NODE_ENV: prod
jobs:
  build:
    name: E2E Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: echo "Is this the CI? $IS_CI"
      - name: Install Safe CLI
        run:  |
          wget "https://github.com/maidsafe/safe-api/releases/download/${{env.SAFE_CLI_VERSION}}/safe-cli-${{env.SAFE_CLI_VERSION}}-x86_64-unknown-linux-gnu.tar.gz" -O ./safe.tar.gz;
          ls .
          mkdir -p $HOME/.safe/safe-cli
          tar -xvzf ./safe.tar.gz -C $HOME/.safe/safe-cli/
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      - name: Install
        run: yarn install --ignore-engines --network-timeout 800000;

      - run: yarn package

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn test-e2e-packed
      - name: So... the job has failed. What do our logs say?
        if: failure()
        run: cat ~/config/safe-network-app/logs/*.log

      # - uses: DevExpress/testcafe-action@latest
      #   with:
      #     args: 'electron:. ./__testcafe__/*.spec.*'
